# Generated by Django 2.2.6 on 2019-10-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Catrgory',
            new_name='Category',
        ),
    ]
